### ISSUE TITLE
Solace client metrics in order to scale my application

### ISSUE THREAD

**Issue by murillocg** [SolaceProducts/solace-spring-boot#76]
I'm migrating from RabbitMQ to Solace, and there's a feature important in my spring boot applications with the rabbitmq client about metrics. We are using the metric `rabbitmq.consumed` to find the rate of consumed messages per second and scaling horizontally after a certain threshold.

I'm able to get this metric because the rabbit client delivers it for me as you can see here: https://blog.rabbitmq.com/posts/2016/11/metrics-support-in-rabbitmq-java-client-4-0/

That said, my question is: The solace client for java (sol-jcsmp) already delivers its metrics? If not, How I can have this metric?

**Comment by Nephery** [comment]
You can get session stats by doing [`JCSMPSession.getSessionStats()`](https://docs.solace.com/API-Developer-Online-Ref-Documentation/java/com/solacesystems/jcsmp/Session.html#getSessionStats--).

Here's the list of stats: https://docs.solace.com/API-Developer-Online-Ref-Documentation/java/com/solacesystems/jcsmp/statistics/StatType.html

I think `TOTAL_MSGS_RECVED` _might_ be what you're looking for.

**Comment by Mrc0113** [comment]
Closing this issue. Let us know if you needed more information @murillocg

**Comment by murillocg** [comment]
Actually, I can't access the object `JCSMPSession` used in your Solace Binder for Spring Cloud Streams.
Do you have some examples using the `JCSMPSession` object in a custom class in a Spring Cloud Streams project?
