### ISSUE TITLE
The plan about supporting Spring Boot 3

### ISSUE THREAD

**Issue by codingzhengsz** [SolaceProducts/solace-spring-boot#90]
Hello, I hope you're good!

I would like to know if there have any plan to support Spring Boot 3?

Thank you!

**Comment by HaloHan2017** [comment]
> Hello, I hope you're good!
> 
> I would like to know if there have any plan to support Spring Boot 3?
> 
> Thank you!

+1

**Comment by Nephery** [comment]
Closed with #95
